extern const GeoLayout actSelect_area_1_geo[];
extern const GeoLayout actSelect_area_1[];
extern const Collision actSelect_area_1_collision[];
extern const MacroObject actSelect_area_1_macro_objs[];
extern Lights1 actSelect_dl_Grass_Example_lights;
extern Vtx actSelect_dl_Level_Mesh_001_mesh_layer_1_vtx_0[4];
extern Gfx actSelect_dl_Level_Mesh_001_mesh_layer_1_tri_0[];
extern Gfx mat_actSelect_dl_Grass_Example[];
extern Gfx mat_revert_actSelect_dl_Grass_Example[];
extern Gfx actSelect_dl_Level_Mesh_001_mesh_layer_1[];
